rules:
  indentation:
    - 2
    - size: 4
  no-ids: 0
  single-line-per-selector: 0
  force-element-nesting: 0
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
  nesting-depth:
    - 2
    - max-depth: 4
