sudo: required
dist: trusty
language: node_js
node_js:
  - stable
script:
  - grunt
  - flake8 *.py **/*.py
before_install:
  - sudo add-apt-repository -y ppa:jonathonf/python-3.6
  - sudo apt-get update
  - sudo apt-get install python3.6 python3.6-dev
  - curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6
install:
  - sudo -H pip3.6 install flake8
  - npm install
