sudo: required
dist: trusty
language: node_js
node_js:
  - stable
script:
  - grunt
  - flake8 *.py **/*.py
before_install:
  - sudo apt-get update
  - sudo apt-get install python3 python3-pip
install:
  - npm install
  - pip3 install flake8
