"""Make fields non-nullable

Revision ID: 4103633b1ae8
Revises: 1d91199c02c5
Create Date: 2017-05-10 12:27:16.654363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4103633b1ae8'
down_revision = '1d91199c02c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('cancelled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('end',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('start',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('reservable',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('banned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('last_login',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('last_login',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('banned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('reservable',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('start',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('end',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('cancelled',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
