"""Add reminded boolean to reservation

Revision ID: 6fcc536a0005
Revises: 4103633b1ae8
Create Date: 2017-05-10 12:28:00.098926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fcc536a0005'
down_revision = '4103633b1ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminded', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('reminded')

    # ### end Alembic commands ###
